---

- hosts: localhost
  tasks:
    - local_action: digital_ocean state=present command=droplet name=obiwan size_id=1gb
                    region_id=nyc2 image_id=13090046 wait_timeout=500 unique_name=yes
      register: reg_droplet

    - debug: msg="ID is {{ reg_droplet.droplet.id }}"

    - debug: msg="IP is {{ reg_droplet.droplet.ip_address }}"

